name: Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -e .
          pip install pytest
          pip install coverage

      - name: Run pytest and check coverage
        run: |
          coverage run -m pytest
          coverage_percentage=$(coverage report | grep "TOTAL" | awk '{print $4}' | tr -d '%'); if [ "$coverage_percentage" -le 0 ]; then echo "Coverage is below acceptable levels!"; exit 1; fi
      
