name: Testing

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      COVERAGE_TOTAL: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -e .
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Load secrets from LOCAL_ENVIRONMENT into environment variables
      - name: Write LOCAL_ENVIRONMENT to a text file
        run: |
          echo "${{ secrets.SECRET_NAME }}" > local_env.txt

      - name: Load environment variables from LOCAL_ENVIRONMENT
        run: |
          while IFS='=' read -r key value; do
            key=$(echo "$key" | xargs)    # Remove leading/trailing spaces from key
            value=$(echo "$value" | xargs) # Remove leading/trailing spaces from value
            echo "$key=$value" >> $GITHUB_ENV
          done < <(grep -v '^#' local_env.txt)

      - name: Access environment variables
        run: |
          echo "Value of a is: $a"
          echo "Value of b is: $b"
          echo "Value of u is: $c"

      - name: Write environment variables to .env file
        run: |
          echo "Writing to .env file..."
          echo "a=$a" >> .env
          echo "b=$b" >> .env
          echo "u=$u" >> .env
          cat .env  # Print the contents of .env file to verify

      - name: Run pytest and generate coverage report
        id: coverage
        run: |
          coverage run --omit='test/*' -m pytest
          coverage report --fail-under=${{ env.COVERAGE_TOTAL }} > coverage_report.txt
          
