name: Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -e .
          pip install pytest
          pip install coverage

      - name: Run pytest and check coverage
        run: |
          coverage run -m pytest
          $coverage_percentage = (coverage report | Select-String "TOTAL" | ForEach-Object { $_.ToString().Split()[-1].Trim('%') }); if ([int]$coverage_percentage -le 0) { echo "Coverage is below acceptable levels!"; exit 1 }
      
